language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t alsgks1218/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true alsgks1218/react-test-app npm run test

after_success:
  - docker build -t alsgks1218/docker-frontend ./frontend
  - docker build -t alsgks1218/docker-backend ./backend
  - docker build -t alsgks1218/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push alsgks1218/docker-frontend
  - docker push alsgks1218/docker-backend
  - docker push alsgks1218/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-test-app"
  env: "DockerTestApp-env"
  bucket_name: elasticbeanstalk-us-east-2-455213246709
  bucket_path: "docker-test-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
